### ISSUE TITLE
TypeError: spec.test.bind is not a function

### ISSUE THREAD

**Issue by Jack-Works** [dfahlander/typeson#15]
Throws at https://github.com/dfahlander/typeson/blob/c2d7277cbf052b592d9f884795bd671c4961b20a/typeson.js#L1045

> TypeError: spec.test.bind is not a function

"typeson": "^5.13.0",
"typeson-registry": "^1.0.0-alpha.29",

code:

`new Typeson().register([require('typeson-registry/presets/builtin')])`

**Comment by brettz9** [comment]
For Node.js, it should be `require('typeson-registry/dist/presets/builtin')`

**Comment by Jack-Works** [comment]
I'm using webpack 🤔 I'll try that

**Comment by Jack-Works** [comment]
That's works for me!
