### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by septs** [dfahlander/typeson#24]
Willing to assist

Welcome Pull Request?

**Comment by brettz9** [comment]
I'm kind of on the fence as far as TS (unless you mean as merely a declaration file), as though I see its benefits, no less for a library about typing, but it also adds some bloat and barriers-to-entry. (I for one am still a relative novice to TS.)

My personal inclination would probably be to let jsdoc and/or declaration files do the trick less obtrusively, but 
I should probably pass on this call to @dfahlander though to see what direction he wants to take the library. 

While it can be helpful to be forced to learn new things, I'm just not sure how well I can help maintain the project if I run into TS issues without having a whole lot of energy to dive into any issues that may come up.

**Comment by septs** [comment]
I hope he becomes a pure TypeScript project

**Comment by septs** [comment]
I think I can transform his start from `typeson-registry`.

**Comment by brettz9** [comment]
What are you thinking of as far as ESM-friendly? Source is of course already in ESM in both projects. What start do you mean?

**Comment by dfahlander** [comment]
I like Typescript, but I think @brettz9's opinions here are the most valuable since you are the major contributor right now. I let @brettz9 decide. One idea would be if @septs made a PR for switching the build script to be using TS (with allowJS) or possibly babel preset-typescript, keeping the source in JS for now except for one or a few modules. That's how I started converting dexie to TS.

**Comment by brettz9** [comment]
I guess typeson is small enough that it should be manageable even with full TS for me to get a fuller sense of things, and then we could look at typeson-registry later on if that works.

**Comment by septs** [comment]
> ESM-friendly

tree shaking is based on es-module and side effects less

https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking

**Comment by brettz9** [comment]
Ah yes, sure. That would indeed be very good, especially for `typeson-registry` with its larger size (though with its source being published and the files being atomic, one can, in the interim, selectively import only the files one needs).

**Comment by septs** [comment]
using typescript define a typeson spec sample

```typescript
export interface SpecObject<T, R, S = unknown> {
  testPlainObjects?: boolean;
  test(value: T): boolean;
  replace?(value: T, state: S): R;
  replaceAsync?(value: T, state: S): Promise<R>;
  revive?(value: R, state: S): T;
  reviveAsync?(value: R, state: S): Promise<T>;
}

export type SpecArray<T, R, S = unknown> = [
  SpecObject<T, R, S>["test"],
  SpecObject<T, R, S>["replace"],
  SpecObject<T, R, S>["revive"]
];

export type SpecFunction = Function;

export type Type<T = unknown, R = unknown, S = unknown> =
  | SpecObject<T, R, S>
  | SpecArray<T, R, S>
  | SpecFunction;

export type TypeObject<T, R, S> = Record<string, Type<T, R, S>>;

export type Preset = Array<Type<unknown, unknown, unknown>>;
```

```typescript
import Typeson from "typeson";
import { SpecObject } from "../define";

const date: SpecObject<Date, number | "NaN"> = {
  test(value) {
    return Typeson.toStringTag(value) === "Date";
  },
  replace(value) {
    const time = value.getTime();
    if (Number.isNaN(time)) {
      return "NaN";
    }
    return time;
  },
  revive(value) {
    if (value === "NaN") {
      return new Date(Number.NaN);
    }
    return new Date(value);
  },
};

export default { date };
```

**Comment by septs** [comment]
but this date is problematic

```
> new Date(0) // in UTC+8 timezone
< Thu Jan 01 1970 08:00:00 GMT+0800 (China Standard Time)

> new Date(0) // in UTC timezone
< Thu Jan 01 1970 00:00:00 GMT+0000 (Greenwich Mean Time)
```

this timestamp will change by time zone

**Comment by brettz9** [comment]
Yeah, that's a critical one to fix too, esp. as its subtlety might give a false sense of success by consumers. Should be addressed in typeson-registry.

**Comment by dfahlander** [comment]
JavaScript Date does not store timezone so there is no problem with encapsulating it using getTime() and reviving it using Date constructor. Using utc string instead of getTime() would not solve anything in that sense.

**Comment by brettz9** [comment]
Per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime 

> getTime() always uses UTC for time representation. For example, a client browser in one timezone, getTime() will be the same as a client browser in any other timezone.

If that had not been the case, one could obtain the [timezone offset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset), but as @dfahlander mentions, that is already taken into account by `getTime`.
