### ISSUE TITLE
Support `BigInt` types

### ISSUE THREAD

**Issue by jlarmstrongiv** [dfahlander/typeson#39]
Support `BigInt` and `BigInt64Array`

[`devalue`](https://www.npmjs.com/package/devalue) supports `BigInt`, but [`typeson`](https://www.npmjs.com/package/typeson) supports the ArrayBuffer types.  

I like [`typeson`](https://www.npmjs.com/package/typeson) and would love to see it support `BigInt` and friends

**Comment by brettz9** [comment]
`typeson-registry` has types for both `BigInt()` and `new Object(BigInt())`. `BigInt64Array` is supported through the registry's typed array type.

Closing, as that should resolve, but feel free to comment further as needed.

**Comment by jlarmstrongiv** [comment]
Oh!  I didn’t `BigInt` listed anywhere in the [README](https://github.com/dfahlander/typeson/blob/master/README.md) so I thought it wasn’t supported.  I’m pleasantly surprised 😄 

I’ve added [`typeson`](https://www.npmjs.com/package/typeson) and it works perfectly—thank you! 🎉

**Comment by brettz9** [comment]
Sure. For others coming here, one can find the types and presets listed at [typeson-registry](https://github.com/dfahlander/typeson-registry).
