### ISSUE TITLE
Problem when array member contains self

### ISSUE THREAD

**Issue by brettz9** [dfahlander/typeson#4]
In my latest commit to `master`, I added some recursive array tests, one of which is failing. I hope to get to debugging this, but if there is any way you might be able to help with these, I would be most grateful.

I also confirmed (in my `pre-brett-changes` branch on my fork) that this problem was present before all of my changes as well.

**Comment by dfahlander** [comment]
Ok, I want to debug this. But I'm in the midst of a hard-to-succeed-deadline for a customer right now + part time parental leave (trying to work when baby is asleep ;). See what I can do at nights. If I forget, please remind me next week. CHeers!

**Comment by brettz9** [comment]
Ok, sure... I appreciate it. And I know, being a daddy is priority. :)

FWIW, I pushed a fix, but I'm not sure it is going to address all cases.

Basically, the problem seems to be that for the cyclic array *member* that references its non-root parent (actually the issue is for *any* such object, and I added another test to this effect for objects), the immediate array parent hasn't quite yet been created in the key iteration loop, so the `getByKeyPath` returns `undefined` and avoids adding any cyclic reference.

I initially tried deferring all of the cyclic resolutions to the end, and although that fixed that particular member problem, revivers that depended on cyclics already being resolved (the cyclic `ImageData` test) would fail.

Deferring the revivers until after all of the deferred cyclic resolutions didn't work either but my stop-gap measure handled both cases by retrying, after each successive loop cycle, any preceding failing `getByKeyPath` if they had failed (since that function should always be returning some object if supplied a properly encapsulated object).

This fix worked for all of our current tests, but I'm just concerned as I don't have a complete mental picture of what ought to be happening and in what order, that it might not do so efficiently or be able to handle all cyclic/reviver cases (e.g., if the reference is in another branch of the object and before it can be discovered, a reviver depends on finding it resolved, assuming that is a possible scenario).

**Comment by brettz9** [comment]
FYI, my fix doesn't seem to have completely solved it, but I haven't had time yet to prepare further test cases (based on what I'm seeing on IndexedDB tests). So if you have time, your own independent review of the problem and my fixes could still be very helpful.

**Comment by brettz9** [comment]
I identified the further issues and pushed my fix. However, I'm still not certain that my series of changes are completely solid. But our IndexedDBShim tests related to cloning are now all passing.

**Comment by dfahlander** [comment]
I'll try to look into it as soon as time allows me to... Still in a deadline project and currently taking part time parental leave with two small kids. Just want to say I'm not ignoring this, even though it may seem I'm not so engaged right now. If I find a time spot some evening this week I will do the review. Please keep reminding me if I forget. Hopefully I will get more time in end of April and forth

**Comment by brettz9** [comment]
This seems to be working, so I think it can be safely closed.

**Comment by dfahlander** [comment]
That's great!
I really struggled with understanding what could cause the issue some weeks ago. But it took me too long time to get to a solution so I had to give it up for then. Glad you solved it.  \O/

**Comment by brettz9** [comment]
Hi, @dfahlander ... With your "issue4b" branch, are you working on an issue fix because you are disinclined to include my other changes or were you just testing things out? I'm curious about your intentions for another release...

**Comment by dfahlander** [comment]
No, I was just pushing old work for backup :) I was cleaning up my hard drive and found non-pushed stuff. Had to erase my hard disk so I didn't just want to throw it away just yet.

**Comment by dfahlander** [comment]
BTW I haven't npm published for quite a while. Should I?

**Comment by brettz9** [comment]
Yes, I think an update would be good--would you like a summary of the changes (or adding a CHANGES.md file)?

**Comment by brettz9** [comment]
Likewise for the registry?

**Comment by dfahlander** [comment]
That would be very nice if you had the posibility.

**Comment by dfahlander** [comment]
CHANGES file sound perfect 👍

**Comment by brettz9** [comment]
I've added one for typeson (as well as doing more revisioning of the README) and am working on one for typeson-registry.

**Comment by brettz9** [comment]
I've now added one for typeson-registry as well (and some doc updates there--though I know it may add some duplication with the "files are the docs", I think it really helps to have an overview as well as a place to provide some additional notes of info and intended usage).

As a reminder before any publishing, typeson-registry's package.json dependency of typeson will need to be updated to indicate the final version as well as naturally the `package.json` versions. I specified new major versions in CHANGES to the presumptive new version numbers.

**Comment by dfahlander** [comment]
Got a failure on npm test on typeson-registry. Seems to be some date string issue:

      AssertionError: expected { Object (a) } to deeply equal { Object (a) }
      + expected - actual

       {
         "a": {
           "age": 30
      -    "dob": "2000-06-19T22:00:00.000Z"
      +    "dob": "2000-06-19T16:00:00.000Z"
           "isMarried": true
           "name": "Bob Smith"
         }
       }

**Comment by brettz9** [comment]
Yeah, sorry... Had been hard-coding an expected timezone string. Fixed.

**Comment by brettz9** [comment]
Also just pushed one minor fix for test names.

**Comment by brettz9** [comment]
And I pushed a change to the registry in separating SpecialNumbers into separate NaN, Infinity, and -Infinity types (with a preset now instead of type to bring them together). (I found separating would be useful in representing IndexedDB keys as `NaN` is not allowed for keys but Infinity and -Infinity are, and I thought granular control might also be a need in other projects.)

**Comment by dfahlander** [comment]
@brettz9 I published typeson 4.0.0 and updated typeson-registry to depend on typeson@^4.0.0. Hope that's ok. I added you as owner of both typeson and typeson-registry at npm so you can control further updates. Thanks for all your work with these libraries!
